"""add agent run cost and output hash

Revision ID: 50fdb89e2a1b
Revises: 85368ac3bc61
"""
from alembic import op
import sqlalchemy as sa


revision = '50fdb89e2a1b'
down_revision = '85368ac3bc61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('cost', sa.JSON(), nullable=True))
    op.add_column('agent_runs', sa.Column('output_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'output_hash')
    op.drop_column('agent_runs', 'cost')
    # ### end Alembic commands ###

